language: go
go: 
 - release
 - tip

services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script: export connectionString=postgres://postgres@localhost:5432/travis_ci_test; go test -v
